# Generated by Django 4.2.5 on 2023-10-25 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_manager', '0005_softwareimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fws', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin', 'tgz', 'tar'])]),
        ),
    ]
